In [2]:
import torch
print(torch.__version__)

2.13.0+cu130


In [3]:
if torch.cuda.is_available():
  print("GPU is Available!")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not Available!")

GPU is Available!
Using GPU: NVIDIA GeForce RTX 5050 Laptop GPU


### **Create trensors**

In [4]:
# Using empty
a = torch.empty(2,3)

In [5]:
# check type
type(a)

torch.Tensor

In [6]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# using rand
torch.rand(2,3)

tensor([[0.4001, 0.5194, 0.5319],
        [0.1496, 0.7073, 0.2697]])

In [9]:
# manula seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
# using tensors
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

## Tensor **Shapes**

In [11]:
x = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.int32)
x

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [12]:
x.shape

torch.Size([2, 3])

In [13]:
torch.empty_like(x)

tensor([[-1560136064,       22960,           0],
        [          0,     6648576,       25971]], dtype=torch.int32)

In [14]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [15]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [16]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [17]:
x.dtype

torch.int32

In [18]:
# to chang data type
torch.tensor([[1,2,3],[4,5,6]], dtype=torch.int32)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [19]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

Methematical Operations

1. Scaler Operation

In [20]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

Tensor Operations on GPU

In [21]:
torch.cuda.is_available()

True

In [22]:
device = torch.device('cuda')

In [23]:
torch.rand((2,3), device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [25]:
a = torch.rand(2,3)
a

tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])

In [ ]:
b = a.to(device)

tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]], device='cuda:0')

In [ ]:
import time

size = 40000

matrix_cpu1 = torch.rand(size, size)
matrix_cpu2 = torch.rand(size, size)


start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1,matrix_cpu2)
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time:.4f} seconds")

matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)
torch.cuda.synchronize()
gpu_time = time.time() - start_time

print(f"Time on GPU: {gpu_time:.4f} seconds")
print("\n Speedup (CPU time / GPU time):", cpu_time / gpu_time)